DELIMITER %
CREATE FUNCTION Validar_Email(email VARCHAR(100))
RETURNS BOOLEAN
DETERMINISTIC
BEGIN
    RETURN (LOCATE('@', email) > 0 AND LOCATE('.', email) > 0);
END%

CREATE FUNCTION Validar_TextoSimples(texto VARCHAR(100))
RETURNS BOOLEAN
DETERMINISTIC
BEGIN
    RETURN texto REGEXP '^[A-Za-zÀ-ÿ0-9 ]+$';
END%

CREATE FUNCTION Validar_NomeCidadeEstado(texto VARCHAR(50))
RETURNS BOOLEAN
DETERMINISTIC
BEGIN
    RETURN texto REGEXP '^[A-Za-zÀ-ÿ ]+$';
END%
DELIMITER %